Wait for require to be available in new windows
To ensure the window at index 2 is loaded prior to the test, add a
wait that explicitly checks for the availability of require. This seems to
solve:

    RuntimeError: unknown error: require is not defined